###########################################
# /!\ MySQL uniquement pour le moment /!\ #
###########################################

host: "localhost"
port: "3306"
db_name: "minecraft"
username: "root"
password: "root"
