zombie: 15
bat: 5
blaze: 100
cave_spider: 20
chicken: 15
cow: 25
creeper: 50
ender_dragon: 50000
enderman: 80
endermite: 5
ghast: 150
guardian: 55
iron_golem: 200
pig: 10
pig_zombie: 30
player: 150
sheep: 30
skeleton: 70
zombie_villager: 30
zombie_horse: 40
wither: 200
spider: 50
wolf: 10